#!/usr/bin/env python3.8
# coding=utf-8

import sys

from umbra.common.app import App
from umbra.agent.main import Agent


class UmbraAgent(App):
    def __init__(self):
        App.__init__(self)

    def run(self, argv):
        ack = self.cfg.parse(argv)
        if ack:
            app_cls = Agent
            self.init(app_cls)
        else:
            print(f"Could not start {self.__class__.__name__}")
            return -1


if __name__ == "__main__":
    app = UmbraAgent()
    app.run(sys.argv[1:])
