#!/usr/bin/env python3.8
# coding=utf-8

import sys

from umbra.common.app import App
from umbra.monitor.main import Monitor


class UmbraMonitor(App):
    def __init__(self):
        App.__init__(self)

    def run(self, argv):
        ack = self.cfg.parse(argv)
        if ack:
            app_cls = Monitor
            self.init(app_cls)
        else:
            print(f"Could not start {self.__class__.__name__}")
            return -1


if __name__ == "__main__":
    app = UmbraMonitor()
    app.run(sys.argv[1:])

